### ISSUE TITLE
message event problem (serial_port_out) with 2.4?

### ISSUE THREAD

**Issue by PTz0uAH** [vAmigaWeb/uat#1] opened 2023-12-15 08:58 UTC
@mithrendal

I've been testing the latest UAT (20231210) and the SERIAL-MIDI from AMIGA->vAmigaWeb works..

Yet the SERIAL-MIDI from vAmigaWeb->AMIGA does not come through..

The debugger does not show a simple logging message [console.log("MIDI FROM 2.4");]..

Can you confirm the  'serial_port_out' message is not fired from 2.4?

**Comment by mithrendal** [comment] 2023-12-15 18:43
Hi @PTz0uAH I will check … possibly it is still broken…

**Comment by mithrendal** [comment] 2023-12-15 21:16
inspection...

test case: booting AROS kickstart (which generates a lot of serial data out ...)

in chrome debugger when looking at the code which sends the `serial_port_out` message 

<img width="1090" alt="image" src="https://github.com/vAmigaWeb/uat/assets/17108995/ac5e02fb-ef9c-4646-a4a3-2e631e77dc2a">

hovering the mouse over the serial out buffer shows that it seems to send data ... 

```
Resident Modules (addr: pri flags ...
```

can you see this in the debugger in your setup  too ?

**Comment by PTz0uAH** [comment] 2023-12-15 22:43
@mithrendal

Yes I can see activity in the debugger when using the vamigaweb.github.io/uat link..

I've copied the zip and updated the TS0CA_UAT yet when testing I am looking at a different line.. and no serial activity.. hmm strange.. I must check the integrity of TS0CA_UAT again.. and a fresh cache..

I 'll get back to you..

some observations:

-  shouldn't `vAmigaWeb_url` in `vAmigaWeb_player.js` point to `https://vamigaweb.github.io/uat/` for testing?
- I've configured it like this.. `vAmigaWeb_url: './'` that worked before..

After comparing 2.4uat vs 2.3 I think I have some more information..

It seems that `2.4uat` is sending a "filtered" output as you can see.. missing midiclocks and sysex.. `which worked in 2.3`..

Here a combined snapshot.. at the left v2.4uat and at the right v2.3..

![debug_24vs23_music-x_001](https://github.com/vAmigaWeb/uat/assets/87427309/29c5f385-12e3-4abe-b4df-10d8c193003d)

note: this explains why my console.log did not log any serial data when Musix-X metronome was set to internal (sample).. together with the missing sysex/clocks the resulting "radio-silence" tricked me into believing serial did not work.. nevertheless v2.4uat shows a strong regression in serial functionality.. imho..

**Comment by mithrendal** [comment] 2023-12-16 21:16
I think I found it ... only positive byte integer values were transferred ... byte values > 127 were not transferred...  

vAmigaCore 2.4
```c++
int
SerialPort::readOutgoingByte()
{
    {   SYNCHRONIZED

        if (outgoing.empty()) return -1;

        int result = outgoing[0];
        outgoing.erase(outgoing.begin());
        return result; 
    }
}
```

vAmigaWeb
```c++
      int byte = amiga->serialPort.readOutgoingByte();
      while(byte>=0)
      {
        send_message_to_js_with_param(message_as_string, byte, data2);
        byte = amiga->serialPort.readOutgoingByte();
      }
```






currently my fix is to mask the integer inside the vAmigaCore ...

vAmigaCore 2.4 patched with a fix
```c++
int
SerialPort::readOutgoingByte()
{
    {   SYNCHRONIZED

        if (outgoing.empty()) return -1;

        int result = outgoing[0];
        outgoing.erase(outgoing.begin());
        return result & 0xff;   //<----------- my current patch 
    }
}
```

**Comment by mithrendal** [comment] 2023-12-16 21:23
pushed out patched version 2.4 to uat...

**Comment by PTz0uAH** [comment] 2023-12-17 04:10
@mithrendal

I'm afraid that did not work and even `broke AmiGoDOS` to some extend.. as the `& 0xFF` masking was already anticipated depending on the chosen mode..

So I debugged a bit deeper and pinpointed the problem "earlier"  in the code..

When pressing PLAY in Music-X it should send a sysex command `0xFC` (MIDI_STOP) as first byte..

At `v2.4uat` the 1st BYTE (int) captured from Music-X is 0x40 (64).. which is part of the metronome sequence and not correct!
_remark: the metronome sequence starts with bytes 0x90 (NOTE_ON CHANNEL 1) 0x40 (key) 0x40 (velocity) so the 0x90 byte was also skipped.._  

At `v2.3` the 1st BYTE (int) captured from Music-X is 0x1FC (508).. which results in 0xFC after masking!

![debug_24vs23_music-x_data001](https://github.com/vAmigaWeb/uat/assets/87427309/529fdeb8-c5fc-4b5b-8074-e1dfef870812)

As you can observe `data` is not filled with the correct value with the v2.4uat..

**Comment by mithrendal** [comment] 2023-12-17 08:35
it looks to me as when the fixed version is not loaded correctly in your last test maybe you could flush the cache and try again ? because with the above fix you should see at least the 0x90 and the 0xFC in the debugger…

here are my tests

1.booting workbench 1.3
2.opening CLI and executing ```type System.info to ser:``` which sends the binary file System.info to the serial port


<img width="609" alt="image" src="https://github.com/vAmigaWeb/uat/assets/17108995/feaa18bc-98c0-407a-ac6e-ee4b74a5d0ba">


that file has the following bytes 0xE3,0x10,…,0xFF

the old version 2.4 transmitted 
0x10,… 🙈

the fixed version 2.4 transmits 
0xE3, 0x10,… 😎

explanation:
the old version skipped negative ints … see here

```c++
int result = outgoing[0];
```

when the 0x90 came in (the first note you mentioned) the result was 0xfffff90 something like that … byte 0x90 corresponds to -144 as a signed byte in decimal. Then later when I was supposed to send it to you there were these vAmigaWeb code lines 

```c++
int byte = amiga->serialPort.readOutgoingByte();
while(byte>=0)
{
    send_message_to_js_with_param(message_as_string, byte, data2);
    byte = amiga->serialPort.readOutgoingByte();
}
```

you see I was skipping the 0x90 because -144 >= 0 is false 

so that should be fixed now … and in my local tests it is …

now to the next issue

> I'm afraid that did not work and even broke AmiGoDOS to some extend.. as the & 0xFF masking was already anticipated depending on the chosen mode..

is your code depending on the data outside of the transmitted byte ? i.e. when the old version sent 0x1fc you need not only the 0xfc from the fixed version but also the 0x100 part of the int ?


Instead of masking I could cast the byte data into a `unsigned int` maybe like in this line ?  


vAmigaCore 2.4
```c++
int result = (unsigned int) outgoing[0]; 
```

I could try … please tell me if that extra meta data is of any worth to you since you wrote it is “already anticipated” … in any case please recheck your setup as the 0x90 should be coming in fine already with the last version… maybe you could do the type System.info to ser: test too and see if the 0xe3 is coming … it is very quick to test…

**Comment by PTz0uAH** [comment] 2023-12-17 13:17
@mithrendal

My current test environment started with a clean cache.. v2.3 and v2.4uat have seperate caches to prevent cache corruption by different versions..

Could you please check one thing..

[`maybe test this afterall..`]
You did send a complete file to test with `type System.info to ser:`  but MIDI relies on realtime BYTEWISE communication (no buffer needed I think)..
all within the timeframe of the baudrate (31250 BAUD for MIDI)..
does it also work for you if the file is only 1 byte in size.. containing i.e. `0xFC` ?

I am going to test some more according to your last answers and produce more elaborate comments..

This is just a quick response.. so I'll report back to you..

**Comment by PTz0uAH** [comment] 2023-12-17 15:11
[report]

observations:

`1.booting workbench 1.3` (Music-X bootdisk]

_WOW when using `1.3 kickstart` (CPU 68000 7Mhz) Music-X MIDI behaves as expected.._

_I was using `3.1 kickstart` (CPU 020E 14Mhz) which worked fine with v2.3.. but seems to behave differently with v2.4uat  that's strange.._

Oops.. seems I was too optimistic.. the url pointed to the v2.3 location..

after fresh cache and using TS0CA_UAT url the same problem rises..

when Music-X starts it sends a 0xFC (MIDI_STOP) cmd.. which is not received.. in the chromium debugger.. hmm..

continue the bughunt...

**Comment by PTz0uAH** [comment] 2023-12-17 18:21
@mithrendal 

Got it to work..

Observations:

"I do not know if it's related to the problem.."

- manifest.json pointed to `uat/` while my local dir is `TS0CA_UAT/` (a warning in chromium debugger)

So.. I revisited my test method and loaded the pure locations without AmiGoDOS for objective comparence:

- test1 location: https://vamigaweb.github.io/uat/
- test2 location: https://amigoxpe.net/uat/

Both with the same Music-X config..

The only thing I changed (for we are running `from subdir only`) was setting the string `vAmigaWeb_url:` to `'./'` inside `vAmigaWeb_player.js` .. which is "root independent" ..

In earlier attempts I also outcommented line 202 `document.getElementById("vAmigaWeb").onload = this.grab_focus;` but now without AmiGoDOS I left it that way.. might also be a factor..

Now it works like expected and the Chromium debugger halts when Music-X starts..

So for now this works.. but from TS0CA_UAT subdir it still not works..

![debug_24vs23_music-x_004](https://github.com/vAmigaWeb/uat/assets/87427309/a57c036f-fbf3-478f-a2a0-5e1be8da171a)

next to do in this test.. activating AmiGoDOS again.. (and outcommenting line 202 in vAmigaWeb_player.js) see what that brings..

to be continued..

**Comment by mithrendal** [comment] 2023-12-17 19:24
here is an explanation of why we see in vAmigaWeb2.3 transmitted numbers higher than 255

http://amiga-dev.wikidot.com/hardware:serdat


<img width="662" alt="image" src="https://github.com/vAmigaWeb/uat/assets/17108995/7e9dd578-119c-4b26-8a49-76abb6340356">


I will change the patched 2.4Core so that it provides the D8 and S bits like the version 2.3 did

**Comment by PTz0uAH** [comment] 2023-12-17 19:58
@mithrendal

thanks for sharing the in-depth aspects.. very enlightning..

`I will change the patched 2.4Core so that it provides the D8 and S bits`

Well at the moment I have no experiments concerning the 9th bit or variable stop-bit position.. most Amiga use-cases I am aware of use plain 8 or 7 bits.. 8N1.. to what situation would the exotic configuration apply ? 7-wire nullmodemcable situations? Serial networking? Only thing I can think of.. the `SMPTE midi protocol` uses 9 bit addressing.. for video synchronising.. which is supported by Music-X 2.0..

[Progress]
I activated AmiGoDOS in the uat/ subfolder and this is the result..

![debug_24uat_music-x](https://github.com/vAmigaWeb/uat/assets/87427309/6cfd2349-b564-49c2-a1ae-10ae1965a54d)

I think we've "cracked" it.. but it raises 3 questions..

1. How important is `manifest.json`.. can I simply edit the file for `TS0CA/ subdir` or is `uat/ subdir` locked into the wasm file during build?
2. Do I need also to adapt the vamigaweb.github.io locations shown in sw.js for my domain?
3. Are underscore characters (as in TS0CA_UAT) when running from subdir allowed?

to be continued..

**Comment by PTz0uAH** [comment] 2023-12-17 21:18
@mithrendal 

latest test /uat

Good news..

The `NULLMODEM0 mode` of `AmiGoDOS `works again.. as tested from `uat/` subdir..

Music-X as "`midislave`" on the `real Amiga 500` is now smoothly following Music-X "`midimaster`" on `vAmigaWeb`..

PLUS..

The other way around also works.. the `real Amiga 500` as "`midimaster`" and `vAmigaWeb` as "`midislave`"!

Glad it works now with `/uat` ..

**Comment by mithrendal** [comment] 2023-12-17 21:47
>I think we've "cracked" it.. but it raises 3 questions..
>How important is manifest.json.. can I simply edit the file for TS0CA/ subdir or is uat/ subdir locked into the wasm file during build?
Do I need also to adapt the vamigaweb.github.io locations shown in sw.js for my domain?
Are underscore characters (as in TS0CA_UAT) when running from subdir allowed?


the wasm binary does not know where it is installed to … i.e. you could also exchange the existing 2.3 binaries with it … the manifest.json start_url simply tells the browser which page it should invoke after installing the app as PWA… in your case it is irrelevant because you are not installing it as a webapp / PWA. 

the manifest scope property defines which web pages belong to the app so that when you are hyper linking inside  the PWA to another webpage whether it should be visible that it is another website… this is also irrelevant when not installed as PWA I think, also we have only one html page and that is the index.html

in the service worker source file it is determined which files should be loaded from cache, when you point it to another subdir then you may end up mixing versions. better just leave it as it is…


I will reenable the transmission of the two extra bits S and D8 in the coming days …   

glad that it works so far on your setup. Do you think it runs better or same as 2.3 ? In my performance tests I saw still a small performance regression don’t know what it is yet. It is not the 40% from the first performance bug which we solved but still around 8% regression… the 2.4 implements various audio filters A500, A1000 low pass and high pass, maybe I will check them…

**Comment by PTz0uAH** [comment] 2023-12-17 23:19
@mithrendal

`Do you think it runs better or same as 2.3`

"feels approximately the same.. with v2.4uat slightly running smoother.. less midi latency.."

I do not really know how to measure the same test-conditions but this is what I did..

At the left v2.4uat at the right v2.3.. not really exact.. but it's something.. (on a PC i7-2600/16Gb/Win10)

![performance_24vs23](https://github.com/vAmigaWeb/uat/assets/87427309/7f379c9a-0d67-4961-9b37-7d805d1364e3)

`the 2.4 implements various audio filters`

well I never used that on the Amiga.. connected to a good old stereo soundsystem but I can imagine one needs such an enhancement when using a modern digital amplifier or mini-speakers in a tablet device..

**Comment by PTz0uAH** [comment] 2023-12-18 00:55
another test..

here a RPi5 performance snapshot of` v2.3` vAmigaWeb running the BatmanGroupDemo at full speed inside TAWS..

![2023-12-18-014134_1920x1080_scrot](https://github.com/vAmigaWeb/uat/assets/87427309/fa48d12e-9c75-46fb-9f00-21668b0de33e)

next I have to adapt the TAWS source to test v2.4uat.. and make another snapshot..

to be continued..

**Comment by PTz0uAH** [comment] 2023-12-18 01:47
another test..

here a RPi5 performance snapshot of `v2.4uat` vAmigaWeb running the BatmanGroupDemo at full speed inside TAWS..

![2023-12-18-023559_1920x1080_scrot](https://github.com/vAmigaWeb/uat/assets/87427309/d349f490-3e76-44b7-910f-dcfe1e12587f)

well that's a pretty good score for such a small machine..

to be continued..

**Comment by mithrendal** [comment] 2024-02-03 18:02
@PTz0uAH currently I have the latest vAmigaCore v2.6beta1 installed on the /uat address … @dirkwhoffmann has bug fixed the original vAmigaCore related to the serial interface besides better accuracy and also speed improvements … therefore my patches related to the serial interface are no longer in … if you have some time you might like to retest the v2.6 beta release

For more info see here https://github.com/dirkwhoffmann/vAmiga/releases

**Comment by PTz0uAH** [comment] 2024-04-01 09:39
@mithrendal ok I will test 2.6 and report..

**Closed as completed** 2024-04-11 10:22 UTC
